apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: frontend
  ports:
  - port: 4200
    targetPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 4200
    targetPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: valdearados/clothing_store_franchise_frontend
        ports:
        - containerPort: 4200
